#!/bin/bash


#Address to mysql motor
#Direccion hacia el motor SQL
rutaMySQL=/usr/bin/mysql


#Name of the file to export to the MySQL database
#Nombre del fichero a exportar a la bbdd en MySQL
nombreFichero=$1


#PATH to csv file
#Ruta al archivo csv
#*** fill put,rellenar
rutaCSV=


#Save the data to have a log control 
#Para tener un log con fecha de cualquiera error
date >>"$rutaCSV"/Logs/MySQLlogExportacion.txt


#To configure the enviriment and local variables shell/console of the process launched for the cron job with UTF-8 format
#Para configurar las variables de ambiente y locales de la shell/consola del proceso lanzado por la tarea cron con el formato UTF-8
export LC_CTYPE=UTF-8


#echo Start....


#Variable a usar
#Variable to use:
if [ -z "$2" ]
  then
    valorColumnas=256
    #echo "You dont put argument so I put the value:" $valorColumnas
else
	valorColumnas=$2
	#echo "Value for Varchars: " $valorColumnas
fi


# Transformar el archivo del formato latin al utf8
#Transform the file from iso_8859_1 latin 1 eur occidental to utf-8 (shell need it)
iconv -f ISO_8859-1 -t UTF-8 "$rutaCSV"/"$nombreFichero".csv > "$rutaCSV"/"$nombreFichero"UTF8.csv 


#In order to delete the double quotes (because mysql has conflict when importing it) sed needs to work on UTF8 format
#Para poder eliminar las comillas dobles (debido a que  mysql tiene conflictos a la hora de importar) sed necesita al archivo  en formato UTF8
sed 's/\"//g' "$rutaCSV"/"$nombreFichero"UTF8.csv  > "$rutaCSV"/"$nombreFichero"UTF8SinComillas.csv 


#Columns or titles of csv file:
#Columnas o titulos del archivo csv :
awk 'BEGIN {FS=";";RS="\n"} {if (NR==1) for (i=1;i<=NF;i++) print $i}' "$rutaCSV"/"$nombreFichero".csv | 
   awk 'BEGIN {FS="\n"; RS=""}  {print $0} '> "$rutaCSV"/resumenColumnas


#To count and know the numbers of columns/titles of csv di and put in the contador variable
#Para contar y saber el numero de campos/titulos del archivo csv y lo pongo en la variable contador
 contador=$(awk 'BEGIN {FS="\n"; RS=""}  {print NF} ' "$rutaCSV"/resumenColumnas)


#Modification of global variable into mysql server in order to turn on  the import option
#Modificacion de la variable global de mysql server para poder activar la opcion de importacion
echo "SET GLOBAL local_infile=ON;" >"$rutaCSV"/tempsqlfile;


#Creation mysql shell script: 
#Crear el scrip de la base de datos sql
echo USE table_BBDD';
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+01:00";
DROP TABLE IF EXISTS '"$nombreFichero"';
'CREATE TABLE "$nombreFichero (" >>"$rutaCSV"/tempsqlfile;


#A loop to put on every variale it's maximum dimesion:
#Bucle para poner en cada variable su maximo valor:
 for ((i=1;i<=$contador;i++)) do echo $(awk 'BEGIN {FS="\r"; RS=""}  {print "`"$'$i'"`"}' "$rutaCSV"/resumenColumnas) varchar"($valorColumnas)" DEFAULT NULL,; 
  done >>"$rutaCSV"/tempsqlfile;


#Sed command to del the last comma
#Comando Sed para borrar la ultima coma del bucle de creacion de los campos varchar 
sed '$s/.$//' <"$rutaCSV"/tempsqlfile >"$rutaCSV"/fileOut.sql


#Set up the last parameters to the table
#Configurando los ultimos parametros de la tabla
echo ") ENGINE=InnoDB DEFAULT CHARSET=utf8;">>"$rutaCSV"/fileOut.sql


#Load the csv file into the BBDD
#Carga del archivo csv dentro de la base de datos 
echo "load data local infile '"$rutaCSV"/"$nombreFichero"UTF8SinComillas.csv' 
 into table $nombreFichero fields terminated by ';' 
 lines terminated by '\\n';" >>"$rutaCSV"/fileOut.sql


#Delete the first row which is the name of the variables ( title) into the csv file
#Borrar la primera columna la cual tiene el nombre de las variables (titulos) exportadas del CSV
echo "DELETE FROM $nombreFichero LIMIT 1;" >>"$rutaCSV"/fileOut.sql


#Para borrar el ultimo salto de linea
#To delete the last end of line
ultimaColumna=$(awk 'END{print}' "$rutaCSV"/resumenColumnas)
#ultimaColumna=$(sed 's/.$//' ultimaColumnatxt);
echo "UPDATE $nombreFichero SET $ultimaColumna = REPLACE($ultimaColumna, '\\r', '');" >>"$rutaCSV"/fileOut.sql


#Para borrar los espacios al inicio y al final de el campo Email
#To delete the white spaces in the start and end in email 
#echo "UPDATE LIS_Pacientes_Mailing_Newsletter SET Email = TRIM(Email);">>"$rutaCSV"/fileOut.sql



#Modification of global variable into mysql server in order to turn off the import option (for security)
#Modificacion de la variable global de mysql server para poder desactivar la opcion de importacion (por seguridad)
echo "SET GLOBAL local_infile=OFF;" >>"$rutaCSV"/fileOut.sql;



#Creation on file error to check any problem with the process of mysql import and load data
#Creacion de un archivo llamado error para comprobar cualquier error en el proceso de carga e importacion del motor sql
#Put the user fater -u and the password after --password
#Colocar el usuario despues de -u y la password despues de --password
#*** fill put,rellenar
"$rutaMySQL" -u  --password= 2>>"$rutaCSV"/Logs/MySQLlogExportacion < "$rutaCSV"/fileOut.sql


##Delete all temporaly files required by shell programs
##Borrar los archivos temporales requiridos por los diferentes programas shell
rm "$rutaCSV"/tempsqlfile 
rm "$rutaCSV"/resumenColumnas 
rm "$rutaCSV"/"$nombreFichero".csv 
rm "$rutaCSV"/fileOut.sql
rm "$rutaCSV"/"$nombreFichero"UTF8SinComillas.csv



#To left the enviroment variables like before the launch of this script
#Para dejar la variable de ambiante y local justo como estaba antes del lanzamiento del script
export LC_CTYPE="en_US.UTF-8"

#Delete the local variables used
#Borrado de las variables locales usadas
unset valorColumnas
unset contador
unset ultimaColumna
unset rutaMySQL
unset rutaCSV


exit 
